/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testingtogether;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricky
 */
public class customer extends javax.swing.JFrame {



    /**
     * Creates new form customerportal
     */
    public customer() {
        initComponents();
        updateSPCombo();
        updateCountryCombo();
        updateCustomerStatusCombo();
        updateReferralCombo();
    }
    
        String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url="jdbc:sqlserver://DESKTOP-RQELHUF\\:1433;databaseName=CIS3365 Shasta Analysts";
        String user="shasta";
        String pass="admin";

        private void updateSPCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from StateProvince";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                pid.addItem(rs.getString("StateProvinceAbbreviation"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
        
        private void updateCountryCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Country";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                cid.addItem(rs.getString("CountryAbbreviation"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
        private void updateCustomerStatusCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from CustomerStatus";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                statusid.addItem(rs.getString("CustomerStatusName"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
        private void updateReferralCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Referral";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                rid.addItem(rs.getString("ReferralType"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();
        first = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        phone2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cphone = new javax.swing.JTextField();
        maddress = new javax.swing.JTextField();
        mcity = new javax.swing.JTextField();
        zcode = new javax.swing.JTextField();
        pid = new javax.swing.JComboBox<>();
        cid = new javax.swing.JComboBox<>();
        statusid = new javax.swing.JComboBox<>();
        rid = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Phone 1");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Last Name ");

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("View Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Buttons");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Customer Info");

        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "Registration Date", "Last Name", "First Name", "Phone 1", "Phone 2", "Email", "SecondaryContactName ", "SecondaryContactPhone", "Mailing Address ", "Mailing City", "StateProvinceID", "MaiingZipCode", "CountryID", "CustomerStatusID", "ReferralID"
            }
        ));
        jScrollPane1.setViewportView(ctable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Phone 2");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Registration Date");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("First Name");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Customer ID");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Email ");

        jLabel3.setText("SecondaryContactName");

        jLabel4.setText("SecondaryContactPhone");

        jLabel11.setText("MailingAddress");

        jLabel13.setText("MailingCity");

        jLabel14.setText("StateProvinceID");

        jLabel15.setText("MailingZipCode");

        jLabel16.setText("CountryID");

        jLabel17.setText("CustomerStatusID");

        jLabel18.setText("ReferralID");

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });

        mcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcityActionPerformed(evt);
            }
        });

        zcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcodeActionPerformed(evt);
            }
        });

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });

        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });

        jMenu10.setText("Home");

        jMenuItem29.setText("Home");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem29);

        jMenuItem30.setText("Welcome  ");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem30);

        jMenuBar1.add(jMenu10);

        jMenu1.setText("Customer");

        jMenuItem2.setText("Customer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Customer Request");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Appointment");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Feedback");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Descision");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Modification");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Warranty");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("WorkOrder");

        jMenuItem10.setText("WorkOrder");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem9.setText("WorkOrder Line");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem11.setText("WorkOrder Line Assignment");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem13.setText("WorkOrder Line Form");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Mileage");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Template");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("SubContractor");

        jMenuItem16.setText("SubContractor");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuItem17.setText("SubContractor Service");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem18.setText("Service");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Employee");

        jMenuItem19.setText("Employee");
        jMenu7.add(jMenuItem19);

        jMenuItem21.setText("Employee Assignment");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuItem22.setText("Purchase Order");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem22);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("HOA");

        jMenuItem24.setText("HOA");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem24);

        jMenuItem25.setText("HOA Request");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem25);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("GOV");

        jMenuItem26.setText("GOV");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem26);

        jMenuItem27.setText("Inspection");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem27);

        jMenuItem28.setText("Permit Request");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem28);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(phone2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(last, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(first, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email)
                                    .addComponent(cname)
                                    .addComponent(cphone)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mcity)
                                    .addComponent(maddress)
                                    .addComponent(zcode)
                                    .addComponent(pid, 0, 187, Short.MAX_VALUE)
                                    .addComponent(cid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statusid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(582, 582, 582))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(maddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(mcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(zcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(cid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(statusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(rid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        try
        { 
            Class.forName(driver);
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String sql="insert into Customer"
                         +"(RegistrationDate,Lastname,Firstname,Phone1,Phone2,Email,SecondaryContactName,SecondaryContactPhone,MailingAddress,MailingCity,StateProvinceID,MailingZipCode,CountryID,CustomerStatusID,ReferralID)"
                          +"values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; 
                    
                    
                    int stateprovid = 0;
            switch (pid.getSelectedItem().toString()){
                case "AL": stateprovid=1;
                            break;
                case "AK": stateprovid=2;
                            break;
                case "AZ": stateprovid=3;
                            break;
                case "AR": stateprovid=4;
                            break;
                case "CA": stateprovid=5;
                            break;
                case "CO": stateprovid=6;
                            break;
                case "CT": stateprovid=7;
                            break;
                case "DE": stateprovid=8;
                            break;
                case "FL": stateprovid=9;
                            break;
                case "GA": stateprovid=10;
                            break;
                case "HI": stateprovid=11;
                            break;
                case "ID": stateprovid=12;
                            break;
                case "IL": stateprovid=13;
                            break;
                case "IN": stateprovid=14;
                            break;
                case "IA": stateprovid=15;
                            break;
                case "KS": stateprovid=16;
                            break;
                case "KY": stateprovid=17;
                            break;
                case "LA": stateprovid=18;
                            break;
                case "ME": stateprovid=19;
                            break;
                case "MD": stateprovid=20;
                            break;
                case "MA": stateprovid=21;
                            break;
                case "MI": stateprovid=22;
                            break;
                case "MN": stateprovid=23;
                            break;
                case "MS": stateprovid=24;
                            break;
                case "MO": stateprovid=25;
                            break;
                case "MT": stateprovid=26;
                            break;
                case "NE": stateprovid=27;
                            break;
                case "NV": stateprovid=28;
                            break;
                case "NH": stateprovid=29;
                            break;
                case "NJ": stateprovid=30;
                            break;
                case "NM": stateprovid=31;
                            break;
                case "NY": stateprovid=32;
                            break;
                case "NC": stateprovid=33;
                            break;
                case "ND": stateprovid=34;
                            break;
                case "OH": stateprovid=35;
                            break;
                case "OK": stateprovid=36;
                            break;
                case "OR": stateprovid=37;
                            break;
                case "PA": stateprovid=38;
                            break;
                case "RI": stateprovid=39;
                            break;
                case "SC": stateprovid=40;
                            break;
                case "SD": stateprovid=41;
                            break;
                case "TN": stateprovid=42;
                            break;
                case "TX": stateprovid=43;
                            break;
                case "UT": stateprovid=44;
                            break;
                case "VT": stateprovid=45;
                            break;
                case "VA": stateprovid=46;
                            break;
                case "WA": stateprovid=47;
                            break;
                case "WV": stateprovid=48;
                            break;
                case "WI": stateprovid=49;
                            break;
                case "WY": stateprovid=50;
                            break;
                case "DC": stateprovid=51;
                            break;
                case "AS": stateprovid=52;
                            break;
                case "GU": stateprovid=53;
                            break;
                case "MP": stateprovid=54;
                            break;
                case "PR": stateprovid=55;
                            break;
                case "VI": stateprovid=56;
                            break;
                case "AG": stateprovid=57;
                            break;
                case "BC": stateprovid=58;
                            break;
                case "BS": stateprovid=59;
                            break;
                case "CM": stateprovid=60;
                            break;
                case "VS": stateprovid=61;
                            break;
                case "DF": stateprovid=62;
                            break;
                case "CH": stateprovid=63;
                            break;
                case "CL": stateprovid=65;
                            break;
                case "DG": stateprovid=66;
                            break;
                case "GT": stateprovid=67;
                            break;
                case "GR": stateprovid=68;
                            break;
                case "HG": stateprovid=69;
                            break;
                case "JA": stateprovid=70;
                            break;
                case "EM": stateprovid=71;
                            break;
                case "NA": stateprovid=74;
                            break;
                case "NL": stateprovid=75;
                            break;
                case "OA": stateprovid=76;
                            break;
                case "PU": stateprovid=77;
                            break;
                case "QT": stateprovid=78;
                            break;
                case "QR": stateprovid=79;
                            break;
                case "SL": stateprovid=80;
                            break;
                case "SI": stateprovid=81;
                            break;
                case "SO": stateprovid=82;
                            break;
                case "TB": stateprovid=83;
                            break;
                case "TM": stateprovid=84;
                            break;
                case "TL": stateprovid=85;
                            break;
                case "VE": stateprovid=86;
                            break;
                case "YU": stateprovid=87;
                            break;
                case "ZA": stateprovid=88;
                            break;
                case "ON": stateprovid=89;
                            break;
                case "QC": stateprovid=90;
                            break;
                case "NS": stateprovid=91;
                            break;
                case "NB": stateprovid=92;
                            break;
                case "MB": stateprovid=93;
                            break;
                case "PE": stateprovid=95;
                            break;
                case "SK": stateprovid=96;
                            break;
                case "AB": stateprovid=97;
                            break;
                case "NT": stateprovid=99;
                            break;
                case "YT": stateprovid=100;
                            break;
                case "NU": stateprovid=101;
            }
            
             int countryid = 0;
            switch (cid.getSelectedItem().toString()){
                case "CN": countryid=1;
                            break;
                case "IN": countryid=2;
                            break;
                case "US": countryid=3;
                            break;
                case "ID": countryid=4;
                            break;
                case "BR": countryid=5;
                            break;
                case "PK": countryid=6;
                            break;
                case "NG": countryid=7;
                            break;
                case "BD": countryid=8;
                            break;
                case "RU": countryid=9;
                            break;
                case "JP": countryid=10;
                            break;
                case "MX": countryid=11;
                            break;
                case "PH": countryid=12;
                            break;
                case "VN": countryid=13;
                            break;
                case "ET": countryid=14;
                            break;
                case "EG": countryid=15;
                            break;
                case "DE": countryid=16;
                            break;
                case "IR": countryid=17;
                            break;
                case "TR": countryid=18;
                            break;
                case "CD": countryid=19;
                            break;
                case "TH": countryid=20;
                            break;
            }
            
            int customerstatusid = 0;
            switch (statusid.getSelectedItem().toString()){
                case "No Work Order": customerstatusid=1;
                            break;
                case "Quote Reuested": customerstatusid=2;
                            break;
                case "Quote Pending": customerstatusid=3;
                            break;
                case "Work Order In Progress": customerstatusid=4;
                            break;
                case "Meeting Scheduled": customerstatusid=5;
                            break;
                case "Work Orders Completed": customerstatusid=6;
                            break;
            }
            
            int referralid = 0;
            switch (statusid.getSelectedItem().toString()){
                case "Word of Mouth": referralid=1;
                            break;
                case "Website": referralid=2;
                            break;
                case "Email": referralid=3;
                            break;
                case "Phone": referralid=4;
                            break;
                case "Advertisement": referralid=5;
                            break;
                case "Social Media": referralid=6;
                            break;
                case "Radio": referralid=7;
                            break;
                 case "Search Engine": referralid=8;
                            break;
                 case "Employee": referralid=9;
                            break;
                  case "Other": referralid=10;
                            break;
            }
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    PreparedStatement pst=con.prepareStatement(sql);     
                    pst.setString(1,date.getText());
                    pst.setString(2,last.getText());
                    pst.setString(3,first.getText());
                    pst.setString(4,phone1.getText());
                    pst.setString(5,phone2.getText());
                    pst.setString(6,email.getText());
                    pst.setString(7,cname.getText());
                    pst.setString(8,cphone.getText());
                    pst.setString(9,maddress.getText());
                    pst.setString(10,mcity.getText());
                    pst.setString(11,String.valueOf(stateprovid));
                    pst.setString(12,zcode.getText());
                    pst.setString(13,String.valueOf(countryid));
                    pst.setString(14,String.valueOf(customerstatusid));
                    pst.setString(15,String.valueOf(referralid));
                    
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Insert Successfully");
                    
                    
                    
    }                                          
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
         
               Connection con=DriverManager.getConnection(url,user,pass);
               String sql="select * from Customer";
               PreparedStatement pst=con.prepareStatement(sql);
               ResultSet rs=pst.executeQuery();
               DefaultTableModel tm=(DefaultTableModel)ctable.getModel();
               tm.setRowCount(0);
               
               while(rs.next())
               {
                   Object o[]={rs.getString("CustomerID"),rs.getString("RegistrationDate"),rs.getString("Lastname"),rs.getString("Firstname"),rs.getString ("Phone1"),rs.getString("Phone2"),rs.getString("Email"),rs.getString("SecondaryContactName"),rs.getString("SecondaryContactPhone"),rs.getString("MailingAddress"),rs.getString("MailingCity"),rs.getString("StateProvinceID"),rs.getString("MailingZipCode"),rs.getString("CountryID"),rs.getString("CustomerStatusID"),rs.getString("ReferralID")};
                   tm.addRow(o);
               }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try
        { 
            Class.forName(driver);
                    Connection con=DriverManager.getConnection(url,user,pass);
                    String sql="update Customer set RegistrationDate=?,Lastname=?,Firstname=?,Phone1=?,Phone2=?,Email=?,SecondaryContactName=?,SecondaryContactPhone=?,MailingAddress=?,MailingCity=?,StateProvinceID=?,MailingZipCode=?,CountryID=?,CustomerStatusID=?,ReferralID=? where CustomerID=?";  
                    PreparedStatement pst=con.prepareStatement(sql);  
                    
                       
                    int stateprovid = 0;
            switch (pid.getSelectedItem().toString()){
                case "AL": stateprovid=1;
                            break;
                case "AK": stateprovid=2;
                            break;
                case "AZ": stateprovid=3;
                            break;
                case "AR": stateprovid=4;
                            break;
                case "CA": stateprovid=5;
                            break;
                case "CO": stateprovid=6;
                            break;
                case "CT": stateprovid=7;
                            break;
                case "DE": stateprovid=8;
                            break;
                case "FL": stateprovid=9;
                            break;
                case "GA": stateprovid=10;
                            break;
                case "HI": stateprovid=11;
                            break;
                case "ID": stateprovid=12;
                            break;
                case "IL": stateprovid=13;
                            break;
                case "IN": stateprovid=14;
                            break;
                case "IA": stateprovid=15;
                            break;
                case "KS": stateprovid=16;
                            break;
                case "KY": stateprovid=17;
                            break;
                case "LA": stateprovid=18;
                            break;
                case "ME": stateprovid=19;
                            break;
                case "MD": stateprovid=20;
                            break;
                case "MA": stateprovid=21;
                            break;
                case "MI": stateprovid=22;
                            break;
                case "MN": stateprovid=23;
                            break;
                case "MS": stateprovid=24;
                            break;
                case "MO": stateprovid=25;
                            break;
                case "MT": stateprovid=26;
                            break;
                case "NE": stateprovid=27;
                            break;
                case "NV": stateprovid=28;
                            break;
                case "NH": stateprovid=29;
                            break;
                case "NJ": stateprovid=30;
                            break;
                case "NM": stateprovid=31;
                            break;
                case "NY": stateprovid=32;
                            break;
                case "NC": stateprovid=33;
                            break;
                case "ND": stateprovid=34;
                            break;
                case "OH": stateprovid=35;
                            break;
                case "OK": stateprovid=36;
                            break;
                case "OR": stateprovid=37;
                            break;
                case "PA": stateprovid=38;
                            break;
                case "RI": stateprovid=39;
                            break;
                case "SC": stateprovid=40;
                            break;
                case "SD": stateprovid=41;
                            break;
                case "TN": stateprovid=42;
                            break;
                case "TX": stateprovid=43;
                            break;
                case "UT": stateprovid=44;
                            break;
                case "VT": stateprovid=45;
                            break;
                case "VA": stateprovid=46;
                            break;
                case "WA": stateprovid=47;
                            break;
                case "WV": stateprovid=48;
                            break;
                case "WI": stateprovid=49;
                            break;
                case "WY": stateprovid=50;
                            break;
                case "DC": stateprovid=51;
                            break;
                case "AS": stateprovid=52;
                            break;
                case "GU": stateprovid=53;
                            break;
                case "MP": stateprovid=54;
                            break;
                case "PR": stateprovid=55;
                            break;
                case "VI": stateprovid=56;
                            break;
                case "AG": stateprovid=57;
                            break;
                case "BC": stateprovid=58;
                            break;
                case "BS": stateprovid=59;
                            break;
                case "CM": stateprovid=60;
                            break;
                case "VS": stateprovid=61;
                            break;
                case "DF": stateprovid=62;
                            break;
                case "CH": stateprovid=63;
                            break;
                case "CL": stateprovid=65;
                            break;
                case "DG": stateprovid=66;
                            break;
                case "GT": stateprovid=67;
                            break;
                case "GR": stateprovid=68;
                            break;
                case "HG": stateprovid=69;
                            break;
                case "JA": stateprovid=70;
                            break;
                case "EM": stateprovid=71;
                            break;
                case "NA": stateprovid=74;
                            break;
                case "NL": stateprovid=75;
                            break;
                case "OA": stateprovid=76;
                            break;
                case "PU": stateprovid=77;
                            break;
                case "QT": stateprovid=78;
                            break;
                case "QR": stateprovid=79;
                            break;
                case "SL": stateprovid=80;
                            break;
                case "SI": stateprovid=81;
                            break;
                case "SO": stateprovid=82;
                            break;
                case "TB": stateprovid=83;
                            break;
                case "TM": stateprovid=84;
                            break;
                case "TL": stateprovid=85;
                            break;
                case "VE": stateprovid=86;
                            break;
                case "YU": stateprovid=87;
                            break;
                case "ZA": stateprovid=88;
                            break;
                case "ON": stateprovid=89;
                            break;
                case "QC": stateprovid=90;
                            break;
                case "NS": stateprovid=91;
                            break;
                case "NB": stateprovid=92;
                            break;
                case "MB": stateprovid=93;
                            break;
                case "PE": stateprovid=95;
                            break;
                case "SK": stateprovid=96;
                            break;
                case "AB": stateprovid=97;
                            break;
                case "NT": stateprovid=99;
                            break;
                case "YT": stateprovid=100;
                            break;
                case "NU": stateprovid=101;
            }
            
             int countryid = 0;
            switch (cid.getSelectedItem().toString()){
                case "CN": countryid=1;
                            break;
                case "IN": countryid=2;
                            break;
                case "US": countryid=3;
                            break;
                case "ID": countryid=4;
                            break;
                case "BR": countryid=5;
                            break;
                case "PK": countryid=6;
                            break;
                case "NG": countryid=7;
                            break;
                case "BD": countryid=8;
                            break;
                case "RU": countryid=9;
                            break;
                case "JP": countryid=10;
                            break;
                case "MX": countryid=11;
                            break;
                case "PH": countryid=12;
                            break;
                case "VN": countryid=13;
                            break;
                case "ET": countryid=14;
                            break;
                case "EG": countryid=15;
                            break;
                case "DE": countryid=16;
                            break;
                case "IR": countryid=17;
                            break;
                case "TR": countryid=18;
                            break;
                case "CD": countryid=19;
                            break;
                case "TH": countryid=20;
                            break;
            }
                   int customerstatusid = 0;
            switch (statusid.getSelectedItem().toString()){
                case "No Work Order": customerstatusid=1;
                            break;
                case "Quote Reuested": customerstatusid=2;
                            break;
                case "Quote Pending": customerstatusid=3;
                            break;
                case "Work Order In Progress": customerstatusid=4;
                            break;
                case "Meeting Scheduled": customerstatusid=5;
                            break;
                case "Work Orders Completed": customerstatusid=6;
                            break;
            }
            
            int referralid = 0;
            switch (statusid.getSelectedItem().toString()){
                case "Word of Mouth": referralid=1;
                            break;
                case "Website": referralid=2;
                            break;
                case "Email": referralid=3;
                            break;
                case "Phone": referralid=4;
                            break;
                case "Advertisement": referralid=5;
                            break;
                case "Social Media": referralid=6;
                            break;
                case "Radio": referralid=7;
                            break;
                 case "Search Engine": referralid=8;
                            break;
                 case "Employee": referralid=9;
                            break;
                  case "Other": referralid=10;
                            break;
            } 
                    
                    
                    
                    
                    
                    
                    
                    
                    
                   
                    pst.setString(1,date.getText());
                    pst.setString(2,last.getText());
                    pst.setString(3,first.getText());
                    pst.setString(4,phone1.getText());
                    pst.setString(5,phone2.getText());
                    pst.setString(6,email.getText());
                    pst.setString(7,cname.getText());
                    pst.setString(8,cphone.getText());
                    pst.setString(9,maddress.getText());
                    pst.setString(10,mcity.getText());
                    pst.setString(11,String.valueOf(stateprovid));
                    pst.setString(12,zcode.getText());
                    pst.setString(13,String.valueOf(countryid));
                    pst.setString(14,String.valueOf(customerstatusid ));
                    pst.setString(15,String.valueOf(referralid));
                     pst.setString(16,id.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Upate Successfully");
                    
                    
                    
    }                                          
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
         
            Class.forName(driver);
            Connection con=DriverManager.getConnection(url,user,pass);
            String sql="Delete from Customer where CustomerID=?";
                            
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, id.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Delete Successfully");
            
        }
            catch(Exception e)
            {
                 JOptionPane.showMessageDialog(this,e.getMessage());
            }     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void mcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcityActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void zcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zcodeActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        new Home ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        new Testinter ().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new customer ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Customer_Request ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Appointment ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new Feedback ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new Decision ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new Modification ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Warranty ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new Work_Order ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Work_Order_Line ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Work_Order_Line_Assignment ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new work_orderline_form ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new Mileage ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        new template ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        new Subcontractor ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        new SubcontractorService ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        new Service ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        new employee_assignment ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        new PurchaseOrder ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        new HOA ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        new HOARequest ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        new Inspection ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        new PermitRequest ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    
                                         
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cid;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cphone;
    private javax.swing.JTable ctable;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField first;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last;
    private javax.swing.JTextField maddress;
    private javax.swing.JTextField mcity;
    private javax.swing.JTextField phone1;
    private javax.swing.JTextField phone2;
    private javax.swing.JComboBox<String> pid;
    private javax.swing.JComboBox<String> rid;
    private javax.swing.JComboBox<String> statusid;
    private javax.swing.JTextField zcode;
    // End of variables declaration//GEN-END:variables
}
