/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testingtogether;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrew Choe
 */
public class HOA extends javax.swing.JFrame {

    /**
     * Creates new form HOA
     */
    public HOA() {
        initComponents();
        updateSPCombo();
        updateCountryCombo();
        
    }
        String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url="jdbc:sqlserver://DESKTOP-RQELHUF\\:1433;databaseName=CIS3365 Shasta Analysts";
        String user="shasta";
        String pass="admin";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HOANametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HOAtable = new javax.swing.JTable();
        ContactNametxt = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        HOAIDtxt = new javax.swing.JTextField();
        HOAPhonetxt = new javax.swing.JTextField();
        HOAAddresstxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HOAEmailtxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Citytxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ZipCodetxt = new javax.swing.JTextField();
        StateProvinceDD = new javax.swing.JComboBox<>();
        btnNew = new javax.swing.JButton();
        countrycombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HOANametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOANametxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("HOA Name");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Contact Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Buttons");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Home Owner Association");

        HOAtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "HOAID", "HOA Name", "Contact Name", "HOA Phone", "HOA Email", "HOA Address", "City", "State Province ID", "Zip Code", "Country ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HOAtable);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("HOAID");

        HOAIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOAIDtxtActionPerformed(evt);
            }
        });

        HOAPhonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOAPhonetxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("HOA Email");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("HOA Phone");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("HOA Address");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("City");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("State Province");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Country ID");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Zip Code");

        StateProvinceDD.setToolTipText("");
        StateProvinceDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateProvinceDDActionPerformed(evt);
            }
        });

        btnNew.setText("View Table");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        countrycombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrycomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StateProvinceDD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContactNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOANametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOAIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOAPhonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOAAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOAEmailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ZipCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countrycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(HOAIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(HOANametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(ContactNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(HOAPhonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HOAEmailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(HOAAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(Citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(StateProvinceDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ZipCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(countrycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void updateSPCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from StateProvince";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                StateProvinceDD.addItem(rs.getString("StateProvinceAbbreviation"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
    
        private void updateCountryCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Country";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                countrycombo.addItem(rs.getString("CountryAbbreviation"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
    
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try
        {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "insert into HOA"
            +"(HOAName, ContactName, HOAPhone, HOAEmail, HOAAddress, City, StateProvinceID, ZipCode, CountryID)"
            +"values(?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
           
            int stateprovid = 0;
            switch (StateProvinceDD.getSelectedItem().toString()){
                case "AL": stateprovid=1;
                            break;
                case "AK": stateprovid=2;
                            break;
                case "AZ": stateprovid=3;
                            break;
                case "AR": stateprovid=4;
                            break;
                case "CA": stateprovid=5;
                            break;
                case "CO": stateprovid=6;
                            break;
                case "CT": stateprovid=7;
                            break;
                case "DE": stateprovid=8;
                            break;
                case "FL": stateprovid=9;
                            break;
                case "GA": stateprovid=10;
                            break;
                case "HI": stateprovid=11;
                            break;
                case "ID": stateprovid=12;
                            break;
                case "IL": stateprovid=13;
                            break;
                case "IN": stateprovid=14;
                            break;
                case "IA": stateprovid=15;
                            break;
                case "KS": stateprovid=16;
                            break;
                case "KY": stateprovid=17;
                            break;
                case "LA": stateprovid=18;
                            break;
                case "ME": stateprovid=19;
                            break;
                case "MD": stateprovid=20;
                            break;
                case "MA": stateprovid=21;
                            break;
                case "MI": stateprovid=22;
                            break;
                case "MN": stateprovid=23;
                            break;
                case "MS": stateprovid=24;
                            break;
                case "MO": stateprovid=25;
                            break;
                case "MT": stateprovid=26;
                            break;
                case "NE": stateprovid=27;
                            break;
                case "NV": stateprovid=28;
                            break;
                case "NH": stateprovid=29;
                            break;
                case "NJ": stateprovid=30;
                            break;
                case "NM": stateprovid=31;
                            break;
                case "NY": stateprovid=32;
                            break;
                case "NC": stateprovid=33;
                            break;
                case "ND": stateprovid=34;
                            break;
                case "OH": stateprovid=35;
                            break;
                case "OK": stateprovid=36;
                            break;
                case "OR": stateprovid=37;
                            break;
                case "PA": stateprovid=38;
                            break;
                case "RI": stateprovid=39;
                            break;
                case "SC": stateprovid=40;
                            break;
                case "SD": stateprovid=41;
                            break;
                case "TN": stateprovid=42;
                            break;
                case "TX": stateprovid=43;
                            break;
                case "UT": stateprovid=44;
                            break;
                case "VT": stateprovid=45;
                            break;
                case "VA": stateprovid=46;
                            break;
                case "WA": stateprovid=47;
                            break;
                case "WV": stateprovid=48;
                            break;
                case "WI": stateprovid=49;
                            break;
                case "WY": stateprovid=50;
                            break;
                case "DC": stateprovid=51;
                            break;
                case "AS": stateprovid=52;
                            break;
                case "GU": stateprovid=53;
                            break;
                case "MP": stateprovid=54;
                            break;
                case "PR": stateprovid=55;
                            break;
                case "VI": stateprovid=56;
                            break;
                case "AG": stateprovid=57;
                            break;
                case "BC": stateprovid=58;
                            break;
                case "BS": stateprovid=59;
                            break;
                case "CM": stateprovid=60;
                            break;
                case "VS": stateprovid=61;
                            break;
                case "DF": stateprovid=62;
                            break;
                case "CH": stateprovid=63;
                            break;
                case "CL": stateprovid=65;
                            break;
                case "DG": stateprovid=66;
                            break;
                case "GT": stateprovid=67;
                            break;
                case "GR": stateprovid=68;
                            break;
                case "HG": stateprovid=69;
                            break;
                case "JA": stateprovid=70;
                            break;
                case "EM": stateprovid=71;
                            break;
                case "NA": stateprovid=74;
                            break;
                case "NL": stateprovid=75;
                            break;
                case "OA": stateprovid=76;
                            break;
                case "PU": stateprovid=77;
                            break;
                case "QT": stateprovid=78;
                            break;
                case "QR": stateprovid=79;
                            break;
                case "SL": stateprovid=80;
                            break;
                case "SI": stateprovid=81;
                            break;
                case "SO": stateprovid=82;
                            break;
                case "TB": stateprovid=83;
                            break;
                case "TM": stateprovid=84;
                            break;
                case "TL": stateprovid=85;
                            break;
                case "VE": stateprovid=86;
                            break;
                case "YU": stateprovid=87;
                            break;
                case "ZA": stateprovid=88;
                            break;
                case "ON": stateprovid=89;
                            break;
                case "QC": stateprovid=90;
                            break;
                case "NS": stateprovid=91;
                            break;
                case "NB": stateprovid=92;
                            break;
                case "MB": stateprovid=93;
                            break;
                case "PE": stateprovid=95;
                            break;
                case "SK": stateprovid=96;
                            break;
                case "AB": stateprovid=97;
                            break;
                case "NT": stateprovid=99;
                            break;
                case "YT": stateprovid=100;
                            break;
                case "NU": stateprovid=101;
            }
            
            
             int countryid = 0;
            switch (countrycombo.getSelectedItem().toString()){
                case "CN": countryid=1;
                            break;
                case "IN": countryid=2;
                            break;
                case "US": countryid=3;
                            break;
                case "ID": countryid=4;
                            break;
                case "BR": countryid=5;
                            break;
                case "PK": countryid=6;
                            break;
                case "NG": countryid=7;
                            break;
                case "BD": countryid=8;
                            break;
                case "RU": countryid=9;
                            break;
                case "JP": countryid=10;
                            break;
                case "MX": countryid=11;
                            break;
                case "PH": countryid=12;
                            break;
                case "VN": countryid=13;
                            break;
                case "ET": countryid=14;
                            break;
                case "EG": countryid=15;
                            break;
                case "DE": countryid=16;
                            break;
                case "IR": countryid=17;
                            break;
                case "TR": countryid=18;
                            break;
                case "CD": countryid=19;
                            break;
                case "TH": countryid=20;
                            break;
            }
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, HOANametxt.getText());
            pst.setString(2, ContactNametxt.getText());
            pst.setString(3, HOAPhonetxt.getText());
            pst.setString(4, HOAEmailtxt.getText());
            pst.setString(5, HOAAddresstxt.getText());
            pst.setString(6, Citytxt.getText());
            pst.setString(7, String.valueOf(stateprovid));
            pst.setString(8, ZipCodetxt.getText());
            pst.setString(9, String.valueOf(countryid));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insert Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try
        {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "update HOA set HOAName = ?, ContactName = ?, HOAPhone = ?,HOAEmail = ?, HOAAddress = ?, City = ?, StateProvinceID = ?, ZipCode = ?, CountryID = ? where HOAID = ?";

            int stateprovid = 0;
            switch (StateProvinceDD.getSelectedItem().toString()){
                case "AL": stateprovid=1;
                            break;
                case "AK": stateprovid=2;
                            break;
                case "AZ": stateprovid=3;
                            break;
                case "AR": stateprovid=4;
                            break;
                case "CA": stateprovid=5;
                            break;
                case "CO": stateprovid=6;
                            break;
                case "CT": stateprovid=7;
                            break;
                case "DE": stateprovid=8;
                            break;
                case "FL": stateprovid=9;
                            break;
                case "GA": stateprovid=10;
                            break;
                case "HI": stateprovid=11;
                            break;
                case "ID": stateprovid=12;
                            break;
                case "IL": stateprovid=13;
                            break;
                case "IN": stateprovid=14;
                            break;
                case "IA": stateprovid=15;
                            break;
                case "KS": stateprovid=16;
                            break;
                case "KY": stateprovid=17;
                            break;
                case "LA": stateprovid=18;
                            break;
                case "ME": stateprovid=19;
                            break;
                case "MD": stateprovid=20;
                            break;
                case "MA": stateprovid=21;
                            break;
                case "MI": stateprovid=22;
                            break;
                case "MN": stateprovid=23;
                            break;
                case "MS": stateprovid=24;
                            break;
                case "MO": stateprovid=25;
                            break;
                case "MT": stateprovid=26;
                            break;
                case "NE": stateprovid=27;
                            break;
                case "NV": stateprovid=28;
                            break;
                case "NH": stateprovid=29;
                            break;
                case "NJ": stateprovid=30;
                            break;
                case "NM": stateprovid=31;
                            break;
                case "NY": stateprovid=32;
                            break;
                case "NC": stateprovid=33;
                            break;
                case "ND": stateprovid=34;
                            break;
                case "OH": stateprovid=35;
                            break;
                case "OK": stateprovid=36;
                            break;
                case "OR": stateprovid=37;
                            break;
                case "PA": stateprovid=38;
                            break;
                case "RI": stateprovid=39;
                            break;
                case "SC": stateprovid=40;
                            break;
                case "SD": stateprovid=41;
                            break;
                case "TN": stateprovid=42;
                            break;
                case "TX": stateprovid=43;
                            break;
                case "UT": stateprovid=44;
                            break;
                case "VT": stateprovid=45;
                            break;
                case "VA": stateprovid=46;
                            break;
                case "WA": stateprovid=47;
                            break;
                case "WV": stateprovid=48;
                            break;
                case "WI": stateprovid=49;
                            break;
                case "WY": stateprovid=50;
                            break;
                case "DC": stateprovid=51;
                            break;
                case "AS": stateprovid=52;
                            break;
                case "GU": stateprovid=53;
                            break;
                case "MP": stateprovid=54;
                            break;
                case "PR": stateprovid=55;
                            break;
                case "VI": stateprovid=56;
                            break;
                case "AG": stateprovid=57;
                            break;
                case "BC": stateprovid=58;
                            break;
                case "BS": stateprovid=59;
                            break;
                case "CM": stateprovid=60;
                            break;
                case "VS": stateprovid=61;
                            break;
                case "DF": stateprovid=62;
                            break;
                case "CH": stateprovid=63;
                            break;
                case "CL": stateprovid=65;
                            break;
                case "DG": stateprovid=66;
                            break;
                case "GT": stateprovid=67;
                            break;
                case "GR": stateprovid=68;
                            break;
                case "HG": stateprovid=69;
                            break;
                case "JA": stateprovid=70;
                            break;
                case "EM": stateprovid=71;
                            break;
                case "NA": stateprovid=74;
                            break;
                case "NL": stateprovid=75;
                            break;
                case "OA": stateprovid=76;
                            break;
                case "PU": stateprovid=77;
                            break;
                case "QT": stateprovid=78;
                            break;
                case "QR": stateprovid=79;
                            break;
                case "SL": stateprovid=80;
                            break;
                case "SI": stateprovid=81;
                            break;
                case "SO": stateprovid=82;
                            break;
                case "TB": stateprovid=83;
                            break;
                case "TM": stateprovid=84;
                            break;
                case "TL": stateprovid=85;
                            break;
                case "VE": stateprovid=86;
                            break;
                case "YU": stateprovid=87;
                            break;
                case "ZA": stateprovid=88;
                            break;
                case "ON": stateprovid=89;
                            break;
                case "QC": stateprovid=90;
                            break;
                case "NS": stateprovid=91;
                            break;
                case "NB": stateprovid=92;
                            break;
                case "MB": stateprovid=93;
                            break;
                case "PE": stateprovid=95;
                            break;
                case "SK": stateprovid=96;
                            break;
                case "AB": stateprovid=97;
                            break;
                case "NT": stateprovid=99;
                            break;
                case "YT": stateprovid=100;
                            break;
                case "NU": stateprovid=101;
            }
            int countryid = 0;
            switch (countrycombo.getSelectedItem().toString()){
                case "CN": countryid=1;
                            break;
                case "IN": countryid=2;
                            break;
                case "US": countryid=3;
                            break;
                case "ID": countryid=4;
                            break;
                case "BR": countryid=5;
                            break;
                case "PK": countryid=6;
                            break;
                case "NG": countryid=7;
                            break;
                case "BD": countryid=8;
                            break;
                case "RU": countryid=9;
                            break;
                case "JP": countryid=10;
                            break;
                case "MX": countryid=11;
                            break;
                case "PH": countryid=12;
                            break;
                case "VN": countryid=13;
                            break;
                case "ET": countryid=14;
                            break;
                case "EG": countryid=15;
                            break;
                case "DE": countryid=16;
                            break;
                case "IR": countryid=17;
                            break;
                case "TR": countryid=18;
                            break;
                case "CD": countryid=19;
                            break;
                case "TH": countryid=20;
                            break;
            }
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, HOANametxt.getText());
            pst.setString(2, ContactNametxt.getText());
            pst.setString(3, HOAPhonetxt.getText());
            pst.setString(4, HOAEmailtxt.getText());
            pst.setString(5, HOAAddresstxt.getText());
            pst.setString(6, Citytxt.getText());
            pst.setString(7, String.valueOf(stateprovid));
            pst.setString(8, ZipCodetxt.getText());
            pst.setString(9, String.valueOf(countryid));
            pst.setString(10, HOAIDtxt.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try
        {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "Delete from HOA where HOAID = ?";

            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, HOAIDtxt.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Delete Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void HOANametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOANametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HOANametxtActionPerformed

    private void HOAIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOAIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HOAIDtxtActionPerformed

    private void HOAPhonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOAPhonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HOAPhonetxtActionPerformed

    private void StateProvinceDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateProvinceDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateProvinceDDActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        
         try
        {
         
               Connection con=DriverManager.getConnection(url,user,pass);
               String sql="select * from HOA";
               PreparedStatement pst=con.prepareStatement(sql);
               ResultSet rs=pst.executeQuery();
               DefaultTableModel hoaTM=(DefaultTableModel)HOAtable.getModel();
               hoaTM.setRowCount(0);
               
               while(rs.next())
               {
                   Object o[]={rs.getString("HOAID"),rs.getString("HOAName"),rs.getString("ContactName"),rs.getString("HOAPhone"),rs.getString("HOAEmail"),rs.getString ("HOAAddress"),rs.getString("City"),rs.getString("StateProvinceID"),rs.getString("ZipCode"),rs.getString("CountryID")};
                   hoaTM.addRow(o);
               }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void countrycomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrycomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countrycomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Citytxt;
    private javax.swing.JTextField ContactNametxt;
    private javax.swing.JTextField HOAAddresstxt;
    private javax.swing.JTextField HOAEmailtxt;
    private javax.swing.JTextField HOAIDtxt;
    private javax.swing.JTextField HOANametxt;
    private javax.swing.JTextField HOAPhonetxt;
    private javax.swing.JTable HOAtable;
    private javax.swing.JComboBox<String> StateProvinceDD;
    private javax.swing.JTextField ZipCodetxt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> countrycombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
