/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testingtogether;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class SubcontractorService extends javax.swing.JFrame {

    public SubcontractorService() {
        initComponents();
        updateServiceCombo();
    }
        String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url="jdbc:sqlserver://DESKTOP-592B8RA\\SQLEXPRESS:1433;databaseName=CIS3365 Shasta Analysts";
        String user="shasta";
        String pass="admin";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubcontractorIDtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubServicetable = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        SubcontractorServiceIDtxt = new javax.swing.JTextField();
        New = new javax.swing.JButton();
        Servicecombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubcontractorIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubcontractorIDtxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Subcontractor ID");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Service ID");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Buttons");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Subcontractor Service");

        SubServicetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subcontractor Service ID", "Sub-Contractor ID", "Service ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SubServicetable);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Subcontractor Service ID");

        SubcontractorServiceIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubcontractorServiceIDtxtActionPerformed(evt);
            }
        });

        New.setText("View Table");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        Servicecombo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubcontractorIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubcontractorServiceIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Servicecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(SubcontractorIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(SubcontractorServiceIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(New))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnInsert)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpdate)
                                    .addComponent(Servicecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateServiceCombo(){
        try{    
        Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Service";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                Servicecombo.addItem(rs.getString("ServiceName"));
            }
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
    
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try
        {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "insert into SubContractorService"
            +"(SubContractorServiceID, ServiceID)"
            +"values(?, ?)";
            
            int serviceid = 0;
            switch (Servicecombo.getSelectedItem().toString()){
                case "Drywall": serviceid=1;
                            break;
                case "Texture": serviceid=2;
                            break;
                case "Roofing": serviceid=3;
                            break;
                case "Demolition": serviceid=4;
                            break;
                case "Fencing": serviceid=5;
                            break;
                case "Covered Deck": serviceid=6;
                            break;
                case "Patio Cover": serviceid=7;
                            break;
                case "Pergola": serviceid=8;
                            break;
                case "Storage Shed": serviceid=9;
                            break;
                case "Insulation": serviceid=10;
                            break;
                case "Framing": serviceid=11;
                            break;
                case "Exterior Wall": serviceid=12;
                            break;
                case "BaseBoard": serviceid=13;
                            break;
                case "Ceiling": serviceid=14;
                            break;
                case "Kitchen Cabnets": serviceid=15;
                            break;
                case "Painting": serviceid=16;
                            break;
                case "Porch": serviceid=17;
                            break;
                case "Gazebo": serviceid=18;
                            break;
                case "Windows": serviceid=19;
                            break;
                case "Siding": serviceid=20;
                            break;
                case "Burglar Bars": serviceid=21;
                            break;
                case "Concrete": serviceid=22;
                            break;
                case "Patio": serviceid=23;
                            break;
                case "Sidewalk": serviceid=24;
                            break;
                case "Parking Lot": serviceid=25;
                            break;
                case "Driveway": serviceid=26;
                            break;
                case "Granite Countertops": serviceid=27;
                            break;
                case "Stamped Concrete": serviceid=28;
                            break;
                case "Color Concrete": serviceid=29;
                            break;
                case "Room Additions": serviceid=30;
                            break;
                case "Add Remove LoadBearing Wall": serviceid=31;
                            break;
                case "Room Conversion": serviceid=32;
                            break;
                case "Electrical": serviceid=34;
                            break;
                case "HVAC": serviceid=35;
                            break;
                case "Basement": serviceid=36;
                            break;
                case "Solar Component": serviceid=37;
                            break;
                case "Pool": serviceid=38;
                            break;
            }
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, SubcontractorIDtxt.getText());
            pst.setString(2, String.valueOf(serviceid));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insert Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try
        {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "update WorkOrderLineAssignment set WorkOrderID = ?, SubContractorID = ? where WorkOrderLineAssignmentID = ?";

             int serviceid = 0;
            switch (Servicecombo.getSelectedItem().toString()){
                case "Drywall": serviceid=1;
                            break;
                case "Texture": serviceid=2;
                            break;
                case "Roofing": serviceid=3;
                            break;
                case "Demolition": serviceid=4;
                            break;
                case "Fencing": serviceid=5;
                            break;
                case "Covered Deck": serviceid=6;
                            break;
                case "Patio Cover": serviceid=7;
                            break;
                case "Pergola": serviceid=8;
                            break;
                case "Storage Shed": serviceid=9;
                            break;
                case "Insulation": serviceid=10;
                            break;
                case "Framing": serviceid=11;
                            break;
                case "Exterior Wall": serviceid=12;
                            break;
                case "BaseBoard": serviceid=13;
                            break;
                case "Ceiling": serviceid=14;
                            break;
                case "Kitchen Cabnets": serviceid=15;
                            break;
                case "Painting": serviceid=16;
                            break;
                case "Porch": serviceid=17;
                            break;
                case "Gazebo": serviceid=18;
                            break;
                case "Windows": serviceid=19;
                            break;
                case "Siding": serviceid=20;
                            break;
                case "Burglar Bars": serviceid=21;
                            break;
                case "Concrete": serviceid=22;
                            break;
                case "Patio": serviceid=23;
                            break;
                case "Sidewalk": serviceid=24;
                            break;
                case "Parking Lot": serviceid=25;
                            break;
                case "Driveway": serviceid=26;
                            break;
                case "Granite Countertops": serviceid=27;
                            break;
                case "Stamped Concrete": serviceid=28;
                            break;
                case "Color Concrete": serviceid=29;
                            break;
                case "Room Additions": serviceid=30;
                            break;
                case "Add Remove LoadBearing Wall": serviceid=31;
                            break;
                case "Room Conversion": serviceid=32;
                            break;
                case "Electrical": serviceid=34;
                            break;
                case "HVAC": serviceid=35;
                            break;
                case "Basement": serviceid=36;
                            break;
                case "Solar Component": serviceid=37;
                            break;
                case "Pool": serviceid=38;
                            break;
            }
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, SubcontractorIDtxt.getText());
            pst.setString(2, String.valueOf(serviceid));
            pst.setString(3, SubcontractorServiceIDtxt.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try
        {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "Delete from SubContractorService where SubContractorServiceID = ?";

            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, SubcontractorServiceIDtxt.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Delete Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void SubcontractorIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubcontractorIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubcontractorIDtxtActionPerformed

    private void SubcontractorServiceIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubcontractorServiceIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubcontractorServiceIDtxtActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:

        try
        {

            Connection con=DriverManager.getConnection(url,user,pass);
            String sql="select * from SubContractorService";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            DefaultTableModel SubSTM;
            SubSTM = (DefaultTableModel)SubServicetable.getModel();
            SubSTM.setRowCount(0);

            while(rs.next())
            {
                Object o[]={rs.getString("SubContractorServiceID"),rs.getString("SubContractorID"),rs.getString("ServiceID")};
                SubSTM.addRow(o);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_NewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubcontractorService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubcontractorService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubcontractorService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubcontractorService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubcontractorService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton New;
    private javax.swing.JComboBox<String> Servicecombo;
    private javax.swing.JTable SubServicetable;
    private javax.swing.JTextField SubcontractorIDtxt;
    private javax.swing.JTextField SubcontractorServiceIDtxt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
